
return Def.ActorFrame{
    Def.Sprite{
        Texture="star.png",
        OnCommand=cmd(blend,"BlendMode_Add";x,_screen.cx+160;y,_screen.cy-290;diffusealpha,0;sleep,8.6;linear,1.7;diffusealpha,1;x,_screen.cx-320;y,_screen.cy+190;);
    };
    Def.Sprite{
        Texture="star.png",
        OnCommand=cmd(blend,"BlendMode_Add";x,_screen.cy+210;y,_screen.cy-240;diffusealpha,0;sleep,9;linear,1.7;diffusealpha,1;x,_screen.cx-270;y,_screen.cy+190;);
    };
    Def.Sprite{
        Texture="star.png",
        OnCommand=cmd(blend,"BlendMode_Add";x,_screen.cx+260;y,_screen.cy-240;diffusealpha,0;sleep,9.4;linear,1.7;diffusealpha,1;x,_screen.cx-220;y,_screen.cy+190;);
    };
    Def.Sprite{
        Texture="star.png",
        OnCommand=cmd(blend,"BlendMode_Add";x,_screen.cx+300;y,_screen.cy-240;diffusealpha,0;sleep,9.8;linear,1.7;diffusealpha,1;x,_screen.cx-180;y,_screen.cy+190;);
    };
    Def.Sprite{
        Texture="star.png",
        OnCommand=cmd(blend,"BlendMode_Add";x,_screen.cx+160;y,_screen.cy-290;diffusealpha,0;sleep,11;linear,1.7;diffusealpha,1;x,_screen.cx-320;y,430;);
    };
    Def.Sprite{
        Texture="star.png",
        OnCommand=cmd(blend,"BlendMode_Add";x,_screen.cx+300;y,_screen.cy-240;diffusealpha,0;sleep,11.5;linear,1.7;diffusealpha,1;x,_screen.cx-180;y,_screen.cy+190;);
    };
    Def.Sprite{
        Texture="star.png",
        OnCommand=cmd(blend,"BlendMode_Add";x,_screen.cx+260;y,_screen.cy-240;diffusealpha,0;sleep,12;linear,1.7;diffusealpha,1;x,_screen.cx-220;y,_screen.cy+190;);
    };
    Def.Sprite{
        Texture="star.png",
        OnCommand=cmd(blend,"BlendMode_Add";x,_screen.cx+260;y,_screen.cy-240;diffusealpha,0;sleep,12;linear,1.7;diffusealpha,1;x,_screen.cx-220;y,_screen.cy+190;);
    };
    Def.Sprite{
        Texture="star.png",
        OnCommand=cmd(blend,"BlendMode_Add";x,_screen.cx+80;y,_screen.cy-290;diffusealpha,0;sleep,12.6;linear,1.7;diffusealpha,1;x,_screen.cx-240;y,_screen.cy+190;);
    };
}